from pathlib import Path
import os

# Define vault paths based on configuration
VAULT_BASE_PATH = Path(os.getenv("VAULT_PATH", "/mnt/c/AI_Hackthon/vault"))

# Folder paths
FOLDER_INBOX = VAULT_BASE_PATH / "INBOX"
FOLDER_NEEDS_ACTION = VAULT_BASE_PATH / "NEEDS_ACTION"
FOLDER_PLAN = VAULT_BASE_PATH / "PLAN"
FOLDER_PENDING_APPROVAL = VAULT_BASE_PATH / "PENDING-APPROVAL"
FOLDER_APPROVED = VAULT_BASE_PATH / "APPROVED"
FOLDER_REJECTED = VAULT_BASE_PATH / "REJECTED"
FOLDER_ARCHIVED = VAULT_BASE_PATH / "ARCHIVED"
FOLDER_LOGS = VAULT_BASE_PATH / "LOGS"

# File paths
FILE_HANDBOOK = VAULT_BASE_PATH / "Company_Handbook.md"
FILE_DASHBOARD = VAULT_BASE_PATH / "dashboard.md"
FILE_STATE_FLAG = FOLDER_LOGS / "STATE_CHANGED.flag"
FILE_LOCK = FOLDER_LOGS / "orchestrator.lock"

# Attachments subdirectory
ATTACHMENTS_SUBDIR = FOLDER_INBOX / "_attachments"